# Site settings
name: Satija Lab
title: Satija Lab
email: rsatija@nygenome.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: satijalab
github_username:  satijalab

# URL locations
member_photos: /img/member_photos/
slideshow_photos: /img/slideshow_photos/
publication_photos: /img/publication_photos/

navpages:
  - name: Home
    link: /
  - name: People
    link: /people/
  - name: Research
    link: /research/
  - name: Publications
    link: /publications/
  - name: Seurat
    link: /seurat/
  - name: Join/Contact
    link: /join_contact/

seurat_nav: /seurat/

# Build settings
markdown: kramdown

